(function(e,t,n,r,i){var s=e(r),o="waypoint.reached",u=function(e,n){e.element.trigger(o,n);if(e.options.triggerOnce){e.element[t]("destroy")}},a=function(e,t){var n=t.waypoints.length-1;while(n>=0&&t.waypoints[n].element[0]!==e[0]){n-=1}
return n},f=[],l=function(t){e.extend(this,{element:e(t),oldScroll:0,waypoints:[],didScroll:false,didResize:false,doScroll:e.proxy(function(){var t=this.element.scrollTop(),r=t>this.oldScroll,i=this,s=e.grep(this.waypoints,function(e,n){return r?e.offset>i.oldScroll&&e.offset<=t:e.offset<=i.oldScroll&&e.offset>t}),o=s.length;if(!this.oldScroll||!t){e[n]("refresh")}
this.oldScroll=t;if(!o){return}
if(!r){s.reverse()}
e.each(s,function(e,t){if(t.options.continuous||e===o-1){u(t,[r?"down":"up"])}})},this)});e(t).scroll(e.proxy(function(){if(!this.didScroll){this.didScroll=true;r.setTimeout(e.proxy(function(){this.doScroll();this.didScroll=false},this),e[n].settings.scrollThrottle)}},this)).resize(e.proxy(function(){if(!this.didResize){this.didResize=true;r.setTimeout(e.proxy(function(){e[n]("refresh");this.didResize=false},this),e[n].settings.resizeThrottle)}},this));s.load(e.proxy(function(){this.doScroll()},this))},c=function(t){var n=null;e.each(f,function(e,r){if(r.element[0]===t){n=r;return false}});return n},h={init:function(r,i){this.each(function(){var s=e.fn[t].defaults.context,u,h=e(this);if(i&&i.context){s=i.context}
if(!e.isWindow(s)){s=h.closest(s)[0]}
u=c(s);if(!u){u=new l(s);f.push(u)}
var p=a(h,u),d=p<0?e.fn[t].defaults:u.waypoints[p].options,v=e.extend({},d,i);v.offset=v.offset==="bottom-in-view"?function(){var t=e.isWindow(s)?e[n]("viewportHeight"):e(s).height();return t-e(this).outerHeight()}:v.offset;if(p<0){u.waypoints.push({element:h,offset:null,options:v})}else{u.waypoints[p].options=v}
if(r){h.bind(o,r)}
if(i&&i.handler){h.bind(o,i.handler)}});e[n]("refresh");return this},remove:function(){return this.each(function(t,n){var r=e(n);e.each(f,function(e,t){var n=a(r,t);if(n>=0){t.waypoints.splice(n,1)}})})},destroy:function(){return this.unbind(o)[t]("remove")}},p={refresh:function(){e.each(f,function(t,r){var i=e.isWindow(r.element[0]),s=i?0:r.element.offset().top,o=i?e[n]("viewportHeight"):r.element.height(),a=i?0:r.element.scrollTop();e.each(r.waypoints,function(e,t){if(!t){return}
var n=t.options.offset,i=t.offset;if(typeof t.options.offset==="function"){n=t.options.offset.apply(t.element)}else{if(typeof t.options.offset==="string"){var f=parseFloat(t.options.offset);n=t.options.offset.indexOf("%")?Math.ceil(o*(f/100)):f}}
t.offset=t.element.offset().top-s+a-n;if(t.options.onlyOnScroll){return}
if(i!==null&&r.oldScroll>i&&r.oldScroll<=t.offset){u(t,["up"])}else{if(i!==null&&r.oldScroll<i&&r.oldScroll>=t.offset){u(t,["down"])}else{if(!i&&a>t.offset){u(t,["down"])}}}});r.waypoints.sort(function(e,t){return e.offset-t.offset})})},viewportHeight:function(){return r.innerHeight?r.innerHeight:s.height()},aggregate:function(){var t=e();e.each(f,function(n,r){e.each(r.waypoints,function(e,n){t=t.add(n.element)})});return t}};e.fn[t]=function(n){if(h[n]){return h[n].apply(this,Array.prototype.slice.call(arguments,1))}else{if(typeof n==="function"||!n){return h.init.apply(this,arguments)}else{if(typeof n==="object"){return h.init.apply(this,[null,n])}else{e.error("Method "+n+" does not exist on jQuery "+t)}}}};e.fn[t].defaults={continuous:true,offset:0,triggerOnce:false,context:r};e[n]=function(e){if(p[e]){return p[e].apply(this)}else{return p.aggregate()}};e[n].settings={resizeThrottle:200,scrollThrottle:100};s.load(function(){e[n]("refresh")})})(jQuery,"waypoint","waypoints",this);(function(e){function t(e){var t=",.?/\\(+-=@~²^)![]{}*&^%$#'\"";var n=t.split("");return n[Math.floor(Math.random()*n.length)]}
e.fn.shuffleLetters=function(n){var r=e.extend({step:20,fps:25,text:"",callback:function(){}},n);return this.each(function(){var n=e(this),i="";if(n.data("animated")){return true}
n.data("animated",true);if(r.text){i=r.text.split("")}else{i=n.text().split("")}
var s=[],o=[];for(var u=0;u<i.length;u++){var a=i[u];if(a==" "){s[u]="space";continue}else if(/[a-z]/.test(a)){s[u]="lowerLetter"}else if(/[A-Z]/.test(a)){s[u]="upperLetter"}else{s[u]="symbol"}
o.push(u)}
n.html("");(function f(e){var u,a=o.length,l=i.slice(0);if(e>a){n.data("animated",false);r.callback(n);return}
for(u=Math.max(e,0);u<a;u++){if(u<e+r.step){l[o[u]]=t(s[o[u]])}else{l[o[u]]=""}}
n.text(l.join(""));setTimeout(function(){f(e+1)},500/r.fps)})(-r.step)})}})(jQuery);(function(e){if(typeof define==="function"&&define.amd){define(["jquery"],e)}else{e(jQuery)}})(function(e){function n(t){return e.isFunction(t)||typeof t=="object"?t:{top:t,left:t}}
var t=e.scrollTo=function(t,n,r){return e(window).scrollTo(t,n,r)};t.defaults={axis:"xy",duration:parseFloat(e.fn.jquery)>=1.3?0:1,limit:true};t.window=function(t){return e(window)._scrollable()};e.fn._scrollable=function(){return this.map(function(){var t=this,n=!t.nodeName||e.inArray(t.nodeName.toLowerCase(),["iframe","#document","html","body"])!=-1;if(!n)return t;var r=(t.contentWindow||t).document||t.ownerDocument||t;return/webkit/i.test(navigator.userAgent)||r.compatMode=="BackCompat"?r.body:r.documentElement})};e.fn.scrollTo=function(r,i,s){if(typeof i=="object"){s=i;i=0}
if(typeof s=="function")s={onAfter:s};if(r=="max")r=9e9;s=e.extend({},t.defaults,s);i=i||s.duration;s.queue=s.queue&&s.axis.length>1;if(s.queue)i/=2;s.offset=n(s.offset);s.over=n(s.over);return this._scrollable().each(function(){function p(e){u.animate(l,i,s.easing,e&&function(){e.call(this,a,s)})}
if(r==null)return;var o=this,u=e(o),a=r,f,l={},c=u.is("html,body");switch(typeof a){case"number":case"string":if(/^([+-]=?)?\d+(\.\d+)?(px|%)?$/.test(a)){a=n(a);break}
a=c?e(a):e(a,this);if(!a.length)return;case"object":if(a.is||a.style)f=(a=e(a)).offset()}
var h=e.isFunction(s.offset)&&s.offset(o,a)||s.offset;e.each(s.axis.split(""),function(e,n){var r=n=="x"?"Left":"Top",i=r.toLowerCase(),d="scroll"+r,v=o[d],m=t.max(o,n);if(f){l[d]=f[i]+(c?0:v-u.offset()[i]);if(s.margin){l[d]-=parseInt(a.css("margin"+r))||0;l[d]-=parseInt(a.css("border"+r+"Width"))||0}
l[d]+=h[i]||0;if(s.over[i])l[d]+=a[n=="x"?"width":"height"]()*s.over[i]}else{var g=a[i];l[d]=g.slice&&g.slice(-1)=="%"?parseFloat(g)/100*m:g}
if(s.limit&&/^\d+$/.test(l[d]))l[d]=l[d]<=0?0:Math.min(l[d],m);if(!e&&s.queue){if(v!=l[d])p(s.onAfterFirst);delete l[d]}});p(s.onAfter);}).end()};t.max=function(t,n){var r=n=="x"?"Width":"Height",i="scroll"+r;if(!e(t).is("html,body"))return t[i]-e(t)[r.toLowerCase()]();var s="client"+r,o=t.ownerDocument.documentElement,u=t.ownerDocument.body;return Math.max(o[i],u[i])-Math.min(o[s],u[s])};return t});(function(e){if(typeof define==="function"&&define.amd){define(["jquery"],e)}else{e(jQuery)}})(function(e){function r(t,n,r){var i=n.hash.slice(1),s=document.getElementById(i)||document.getElementsByName(i)[0];if(!s)return;if(t)t.preventDefault();var o=e(r.target);if(r.lock&&o.is(":animated")||r.onBefore&&r.onBefore(t,s,o)===false)return;if(r.stop)o._scrollable().stop(true);if(r.hash){var u=s.id===i?"id":"name",a=e("<a> </a>").attr(u,i).css({position:"absolute",top:e(window).scrollTop(),left:e(window).scrollLeft()});s[u]="";e("body").prepend(a);location.hash=n.hash;a.remove();s[u]=i}
o.scrollTo(s,r).trigger("notify.serialScroll",[s])}
var t=location.href.replace(/#.*/,"");var n=e.localScroll=function(t){e("body").localScroll(t)};n.defaults={duration:1e3,axis:"y",event:"click",stop:true,target:window};e.fn.localScroll=function(i){function s(){return!!this.href&&!!this.hash&&this.href.replace(this.hash,"")==t&&(!i.filter||e(this).is(i.filter))}
i=e.extend({},n.defaults,i);if(i.hash&&location.hash){if(i.target)window.scrollTo(0,0);r(0,location,i)}
return i.lazy?this.on(i.event,"a,area",function(e){if(s.call(this)){r(e,this,i)}}):this.find("a,area").filter(s).bind(i.event,function(e){r(e,this,i)}).end().end();};n.hash=function(){};return n});(function(e){var t={},n,r,i=document,s=window,o=i.documentElement,u=e.expando;e.event.special.inview={add:function(n){t[n.guid+"-"+this[u]]={data:n,$element:e(this)}},remove:function(e){try{delete t[e.guid+"-"+this[u]]}catch(n){}}};e(s).bind("scroll resize",function(){n=r=null});!o.addEventListener&&o.attachEvent&&o.attachEvent("onfocusin",function(){r=null});setInterval(function(){var u=e(),l,c=0;e.each(t,function(e,t){var n=t.data.selector,r=t.$element;u=u.add(n?r.find(n):r)});if(l=u.length){var v;if(!(v=n)){var m={height:s.innerHeight,width:s.innerWidth};if(!m.height&&((v=i.compatMode)||!e.support.boxModel))v="CSS1Compat"===v?o:i.body,m={height:v.clientHeight,width:v.clientWidth};v=m}
n=v;for(r=r||{top:s.pageYOffset||o.scrollTop||i.body.scrollTop,left:s.pageXOffset||o.scrollLeft||i.body.scrollLeft};c<l;c++)
if(e.contains(o,u[c])){v=e(u[c]);var g=v.height(),y=v.width(),b=v.offset(),m=v.data("inview");if(!r||!n)break;b.top+g>r.top&&b.top<r.top+n.height&&b.left+y>r.left&&b.left<r.left+n.width?(y=r.left>b.left?"right":r.left+n.width<b.left+y?"left":"both",g=r.top>b.top?"bottom":r.top+n.height<b.top+g?"top":"both",b=y+"-"+g,(!m||m!==b)&&v.data("inview",b).trigger("inview",[!0,y,g])):m&&v.data("inview",!1).trigger("inview",[!1])}}},250)})(jQuery);"use strict";(function(e){if(typeof exports==="object"){module.exports=e()}else if(typeof define==="function"&&define.amd){define(e)}else{window.WatchJS=e();window.watch=window.WatchJS.watch;window.unwatch=window.WatchJS.unwatch;window.callWatchers=window.WatchJS.callWatchers}})(function(){var e={noMore:false},t=[];var n=function(e){var t={};return e&&t.toString.call(e)=="[object Function]"};var r=function(e){return e%1===0};var i=function(e){return Object.prototype.toString.call(e)==="[object Array]"};var s=function(e,t){var n=[],r=[];if(!(typeof e=="string")&&!(typeof t=="string")){if(i(e)){for(var s=0;s<e.length;s++){if(t[s]===undefined)n.push(s)}}else{for(var s in e){if(e.hasOwnProperty(s)){if(t[s]===undefined){n.push(s)}}}}
if(i(t)){for(var o=0;o<t.length;o++){if(e[o]===undefined)r.push(o)}}else{for(var o in t){if(t.hasOwnProperty(o)){if(e[o]===undefined){r.push(o)}}}}}
return{added:n,removed:r}};var o=function(e){if(null==e||"object"!=typeof e){return e}
var t=e.constructor();for(var n in e){t[n]=e[n]}
return t};var u=function(e,t,n,r){try{Object.observe(e[t],function(e){r(e)})}catch(i){try{Object.defineProperty(e,t,{get:n,set:r,enumerable:true,configurable:true})}catch(s){try{Object.prototype.__defineGetter__.call(e,t,n);Object.prototype.__defineSetter__.call(e,t,r)}catch(o){throw new Error("watchJS error: browser not supported :/")}}}};var a=function(e,t,n){try{Object.defineProperty(e,t,{enumerable:false,configurable:true,writable:false,value:n})}catch(r){e[t]=n}};var f=function(){if(n(arguments[1])){l.apply(this,arguments)}else if(i(arguments[1])){c.apply(this,arguments)}else{h.apply(this,arguments)}};var l=function(e,t,n,r){if(typeof e=="string"||!(e instanceof Object)&&!i(e)){return}
var s=[];if(i(e)){for(var o=0;o<e.length;o++){s.push(o)}}else{for(var u in e){if(e.hasOwnProperty(u)){s.push(u)}}}
c(e,s,t,n,r);if(r){x(e,"$$watchlengthsubjectroot",t,n)}};var c=function(e,t,n,r,s){if(typeof e=="string"||!(e instanceof Object)&&!i(e)){return}
for(var o=0;o<t.length;o++){var u=t[o];h(e,u,n,r,s)}};var h=function(e,t,r,s,o){if(typeof e=="string"||!(e instanceof Object)&&!i(e)){return}
if(n(e[t])){return}
if(e[t]!=null&&(s===undefined||s>0)){l(e[t],r,s!==undefined?s-1:s)}
m(e,t,r,s);if(o&&(s===undefined||s>0)){x(e,t,r,s)}};var p=function(){if(n(arguments[1])){d.apply(this,arguments)}else if(i(arguments[1])){v.apply(this,arguments)}else{E.apply(this,arguments)}};var d=function(e,t){if(e instanceof String||!(e instanceof Object)&&!i(e)){return}
if(i(e)){var n=[];for(var r=0;r<e.length;r++){n.push(r)}
v(e,n,t)}else{var s=function(e){var n=[];for(var r in e){if(e.hasOwnProperty(r)){if(e[r]instanceof Object){s(e[r])}else{n.push(r)}}}
v(e,n,t)};s(e)}};var v=function(e,t,n){for(var r in t){if(t.hasOwnProperty(r)){E(e,t[r],n)}}};var m=function(t,n,r,i){var s=t[n];w(t,n);if(!t.watchers){a(t,"watchers",{})}
if(!t.watchers[n]){t.watchers[n]=[]}
for(var o=0;o<t.watchers[n].length;o++){if(t.watchers[n][o]===r){return}}
t.watchers[n].push(r);var f=function(){return s};var c=function(o){var u=s;s=o;if(i!==0&&t[n]){l(t[n],r,i===undefined?i:i-1)}
w(t,n);if(!e.noMore){if(u!==o){g(t,n,"set",o,u);e.noMore=false}}};u(t,n,f,c)};var g=function(e,t,n,r,i){if(t!==undefined){for(var s=0;s<e.watchers[t].length;s++){e.watchers[t][s].call(e,t,n,r,i)}}else{for(var t in e){if(e.hasOwnProperty(t)){g(e,t,n,r,i)}}}};var y=["pop","push","reverse","shift","sort","slice","unshift"];var b=function(e,t,n,r){a(e[t],r,function(){var i=n.apply(e[t],arguments);h(e,e[t]);if(r!=="slice"){g(e,t,r,arguments)}
return i})};var w=function(e,t){if(!e[t]||e[t]instanceof String||!i(e[t])){return}
for(var n=y.length,r;n--;){r=y[n];b(e,t,e[t][r],r)}};var E=function(e,t,n){for(var r=0;r<e.watchers[t].length;r++){var i=e.watchers[t][r];if(i==n){e.watchers[t].splice(r,1)}}
T(e,t,n)};var S=function(){for(var e=0;e<t.length;e++){var n=t[e];if(n.prop==="$$watchlengthsubjectroot"){var r=s(n.obj,n.actual);if(r.added.length||r.removed.length){if(r.added.length){c(n.obj,r.added,n.watcher,n.level-1,true)}
n.watcher.call(n.obj,"root","differentattr",r,n.actual)}
n.actual=o(n.obj)}else{var r=s(n.obj[n.prop],n.actual);if(r.added.length||r.removed.length){if(r.added.length){for(var i=0;i<n.obj.watchers[n.prop].length;i++){c(n.obj[n.prop],r.added,n.obj.watchers[n.prop][i],n.level-1,true)}}
g(n.obj,n.prop,"differentattr",r,n.actual)}
n.actual=o(n.obj[n.prop])}}};var x=function(e,n,r,i){var s;if(n==="$$watchlengthsubjectroot"){s=o(e)}else{s=o(e[n])}
t.push({obj:e,prop:n,actual:s,watcher:r,level:i})};var T=function(e,n,r){for(var i=0;i<t.length;i++){var s=t[i];if(s.obj==e&&s.prop==n&&s.watcher==r){t.splice(i,1)}}};setInterval(S,50);e.watch=f;e.unwatch=p;e.callWatchers=g;return e})